name: Deploy Stable to GitHub Pages

on:
  push:
    tags:
      - 'v*' # Запускаем строго по тегу релиза (например v1.0.0)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-stable"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build
        run: npm run build
        env:
          BASE_PATH: ${{ steps.pages.outputs.base_path == '/' && '' || steps.pages.outputs.base_path }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    # Использование отдельного Environment ("production") позволяет 
    # включить "Required reviewers" в настройках репозитория.
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
